# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
# cache: packages

warnings_are_errors: false


env:
  global:
    - PYTORCH_VERSION="1.6"
    - PYTHON_VERSION="3.6"

r-packages:
  - logging
  - reticulate
  - jsonlite
  - R6
  - rstudioapi
  - data.table


before_script:
# do not need these commented lines
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export LD_LIBRARY_PATH=${TRAVIS_HOME}/miniconda/envs/r-torch/lib
  - echo $PATH
  - echo $LD_LIBRARY_PATH
  - hash -r
  - rm miniconda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - R CMD INSTALL .
  # - R -e 'rTorch::install_pytorch(method="conda", version=Sys.getenv("PYTORCH_VERSION"), channel="pytorch", conda_python_version="3.6")'
  - sudo rm /usr/lib/x86_64-linux-gnu/libstdc++.so.6
  # - R -e 'rTorch:::install_conda(package=paste0("pytorch=", Sys.getenv("PYTORCH_VERSION")), envname="r-torch", conda="auto", conda_python_version=Sys.getenv("PYTHON_VERSION"), pip=FALSE, channel="pytorch", extra_packages=c("torchvision", "cpuonly", "matplotlib", "pandas"))'
  - R -e 'rTorch:::install_conda(package="pytorch=1.6"), envname="r-torch", conda="auto", conda_python_version="3.6", pip=FALSE, channel="pytorch", extra_packages=c("torchvision", "cpuonly", "matplotlib", "pandas"))'



